USE INFOADB;


CREATE TABLE TB_CADASTRO_CLIENTE (

	ID_CLIENTE 			INT PRIMARY KEY AUTO_INCREMENT,	
	NM_CLIENTE 			VARCHAR(200),
	NM_SOBRENOME 		VARCHAR(200),
	DS_CPF 				VARCHAR(14),
	DS_TELEFONE 		VARCHAR(15),
	NM_USUARIO			VARCHAR(200),
	DS_EMAIL 			VARCHAR(200),
	DS_SENHA	 		VARCHAR(200)

);

CREATE TABLE TB_CADASTRO_EMPRESA (

	ID_EMPRESA 					INT PRIMARY KEY AUTO_INCREMENT,
	DS_CNPJ 					VARCHAR(18),
	NM_RAZAO_SOCIAL 			VARCHAR(200),
	DS_EMAIL_EMPRESA 			VARCHAR(200),
	DS_SENHA_EMPRESA 			VARCHAR(200),
	DS_ENDERECO_EMPRESA 		VARCHAR(200)

);

CREATE TABLE TB_CADASTRO_ADM (

	ID_ADM 				INT PRIMARY KEY AUTO_INCREMENT,
	DS_EMAIL_ADM 		VARCHAR(200),
	DS_SENHA_ADM 		VARCHAR(200)
    
);


{
  "Nome": "Eric",
  "Sobrenome": "Tasa",
  "CPF": "499.333.100-90",
  "Telefone": "(11) 96777-9088",
  "NomeUsuario": "Tuu",
  "Email": "epp@gmail.com",
  "Senha": "123456"
}

{
  "CNPJ": "33344983983",
  "RazaoSocial": "MC donalds",
  "Email": "mc@gmail.com",
  "Senha": "1234",
  "Endereco": "av. para"
}